### ISSUE TITLE
Dynamic nav component

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479-sp-2022/tool-exchange#29]
The navigation layout component needs to become dynamic so both logged in and guest users can use the same nav.

Acceptance criteria:
- All pages on the site use the same navigation component via the app layout component
- For now the main navigation links are home (via the logo image) and /tools
- The dropdown on the right contains /login and /register links if the user is a guest
- The dropdown on the right contains /profile and /logout links if the user is logged in
- **NOTE** make sure to update both nav elements with this logic, the component contains both a desktop and a mobile nav

**Comment by oldskoolfan** [comment]
@FarhanB2 how is this coming along? any questions?

**Comment by FarhanB2** [comment]
> 

I'm still working on another issue I will start on this one soon.
