### ISSUE TITLE
Create tool list route and view

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479-sp-2022/tool-exchange#4]
As a user I want a place to browse a list of tools on the site.

Acceptance Criteria:
- There is a ToolController for handling routes related to tools
- There is a route called /tools
- There is a view called tool-list
- The top nav bar links to the /tools route
- For now a simple placeholder for the tool list data will suffice

**Comment by josephambrozich** [comment]
Hey Harrison, I'm not sure if you've published your branch for this yet, but I accidentally fulfilled this in my PR too, so can you look that over and make sure we don't have any conflicts? Thanks!
